eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-services:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICES/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
insurance:
  provider:
    uri: http://localhost:7070/insurence/allPlan
